# yamllint disable rule:line-length
---
configPreset: large
infrahub:
  infrahubServer:
    replicas: 4
  infrahubTaskWorker:
    replicas: 8
    infrahubTaskWorker:
      env:
        INFRAHUB_PAGINATION_SIZE: "1000"
  neo4j:
    neo4j:
      resources:
        limits:
          cpu: "16"
          memory: "64Gi"
        requests:
          cpu: "16"
          memory: "64Gi"
    config:
      server.memory.heap.initial_size: "31G"
      server.memory.heap.max_size: "31G"
      server.memory.pagecache.size: "16G"
  prefect-server:
    postgresql:
      primary:
        extraEnvVars:
          - name: POSTGRESQL_MAX_CONNECTIONS
            value: "500"
    server:
      replicaCount: 4
      env:
        - name: PREFECT_UI_SERVE_BASE
          value: /
        - name: PREFECT__SERVER_WEBSERVER_ONLY
          value: "true"
        - name: PREFECT_SERVER_SERVICES_EVENT_LOGGER_ENABLED
          value: "false"
        - name: PREFECT_SERVER_SERVICES_EVENT_PERSISTER_ENABLED
          value: "false"
        - name: PREFECT_SERVER_SERVICES_TRIGGERS_ENABLED
          value: "false"
        - name: PREFECT_SERVER_SERVICES_TASK_RUN_RECORDER_ENABLED
          value: "false"
        - name: PREFECT_API_BLOCKS_REGISTER_ON_START
          value: "false"
        - name: WEB_CONCURRENCY
          value: "1"
        - name: PREFECT_REDIS_MESSAGING_PUBLISHER_BATCH_SIZE
          value: "20"
    backgroundServices:
      replicaCount: 2
      runAsSeparateDeployment: true
      messaging:
        redis:
          host: "example-infrahub-cache-master" # Set correct hostname
          db: 1
      args:
        - sh
        - -c
        - "while true; do if curl -s -o /dev/null http://prefect-server:4200; then break; fi; sleep 10; echo try; done; prefect server services start"
      env:
        - name: PREFECT_SERVER_SERVICES_EVENT_LOGGER_ENABLED
          value: "true"
        - name: PREFECT_SERVER_SERVICES_EVENT_PERSISTER_ENABLED
          value: "true"
        - name: PREFECT_SERVER_SERVICES_TRIGGERS_ENABLED
          value: "true"
        - name: PREFECT_SERVER_SERVICES_TASK_RUN_RECORDER_ENABLED
          value: "true"
        - name: PREFECT_API_BLOCKS_REGISTER_ON_START
          value: "false"
        - name: PREFECT_REDIS_MESSAGING_PUBLISHER_BATCH_SIZE
          value: "20"
        - name: PREFECT_SERVER_SERVICES_EVENT_PERSISTER_READ_BATCH_SIZE
          value: "80"
        - name: PREFECT_SERVER_SERVICES_EVENT_PERSISTER_BATCH_SIZE
          value: "80"
        - name: PREFECT_SERVER_SERVICES_TASK_RUN_RECORDER_READ_BATCH_SIZE
          value: "20"
        - name: PREFECT_SERVER_SERVICES_TASK_RUN_RECORDER_BATCH_SIZE
          value: "20"