# yamllint disable rule:line-length
---
infrahub:
  global:
    kubernetesClusterDomain: cluster.local
    infrahubRepository: opsmill/infrahub-enterprise
    imagePullPolicy: IfNotPresent
  infrahubServer:
    podSecurityContext:
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
      fsGroup: 1000
    infrahubServer:
      securityContext:
        allowPrivilegeEscalation: false
      args:
        - gunicorn
        - --config
        - /source/community/backend/infrahub/serve/gunicorn_config.py
        - -w
        - "2"
        - --logger-class
        - infrahub.serve.log.GunicornLogger
        - infrahub_enterprise.server:app
      env:
        - name: INFRAHUB_ALLOW_ANONYMOUS_ACCESS
          value: "true"
        - name: INFRAHUB_CACHE_PORT
          value: "6379"
        - name: INFRAHUB_DB_TYPE
          value: "neo4j"
        - name: INFRAHUB_LOG_LEVEL
          value: "INFO"
        - name: INFRAHUB_PRODUCTION
          value: "false"
        - name: INFRAHUB_INITIAL_ADMIN_TOKEN
          value: "06438eb2-8019-4776-878c-0941b1f1d1ec"
        - name: INFRAHUB_SECURITY_SECRET_KEY
          value: "327f747f-efac-42be-9e73-999f08f86b92"
        - name: INFRAHUB_GIT_REPOSITORIES_DIRECTORY
          value: "/opt/infrahub/git"
        - name: INFRAHUB_WORKFLOW_ADDRESS
          value: "prefect-server"
        - name: INFRAHUB_WORKFLOW_PORT
          value: "4200"
        - name: INFRAHUB_WORKFLOW_DEFAULT_WORKER_TYPE
          value: "infrahubentasync"
        - name: PREFECT_API_URL
          value: "http://prefect-server:4200/api"
  infrahubTaskWorker:
    podSecurityContext:
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
      fsGroup: 1000
    infrahubTaskWorker:
      securityContext:
        allowPrivilegeEscalation: false
      args:
        - prefect
        - worker
        - start
        - --type
        - infrahubentasync
        - --pool
        - infrahub-worker
        - --with-healthcheck
  infrahubDemoData:
    command:
      - sh
      - -c
      - "infrahubctl schema load community/models/base --wait 30 && infrahubctl run community/models/infrastructure_edge.py && infrahubctl menu load community/models/base_menu.yml && infrahubctl repository add demo-edge https://github.com/opsmill/infrahub-demo-edge --read-only"
  neo4j:
    neo4j:
      edition: "enterprise"
      acceptLicenseAgreement: "yes"
  prefect-server:
    global:
      prefect:
        image:
          repository: registry.opsmill.io/opsmill/infrahub-enterprise
    server:
      command:
        - /usr/bin/tini
        - -g
        - --
      args:
        - sh
        - -c
        - "env INFRAHUB_CACHE_ADDRESS=$PREFECT_REDIS_MESSAGING_HOST gunicorn -k uvicorn.workers.UvicornWorker -b 0.0.0.0:4200 'infrahub.prefect_server.app:create_infrahub_prefect()'"
      env:
      - name: PREFECT_UI_SERVE_BASE
        value: /
      - name: PREFECT__SERVER_WEBSERVER_ONLY
        value: "true"
      podSecurityContext:
        runAsUser: 1000
        fsGroup: 1000
      containerSecurityContext:
        runAsUser: 1000
        readOnlyRootFilesystem: false
    migrations:
      enabled: false # Migrations are handled by custom Infrahub Prefect entrypoint
    backgroundServices:
      runAsSeparateDeployment: false
      command:
        - /usr/bin/tini
        - -g
        - --
      podLabels:
        infrahub/service: task-manager