{{- if .Values.infrahubDemoData.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "infrahub-helm.fullname" . }}-infrahub-demo-data-job
  namespace: "{{ .Release.Namespace }}"
  labels:
  {{- include "infrahub-helm.labels" . | nindent 4 }}
  annotations:
  {{- include "infrahub-helm.annotations" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.infrahubDemoData.backoffLimit }}
  template:
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.infrahubDemoData.podSecurityContext }}
      securityContext: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.infrahubDemoData.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.infrahubDemoData.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.infrahubDemoData.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.infrahubDemoData.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - command:
          {{- toYaml .Values.infrahubDemoData.command | nindent 12 }}
          env:
          {{- include "infrahub-helm.infrahubDemoData.defaultEnv" . | nindent 12 }}
          {{- with .Values.infrahubDemoData.env }}
            {{- range $key, $value := . }}
            {{- if or $value (not (or (eq $key "INFRAHUB_INITIAL_ADMIN_TOKEN") (eq $key "INFRAHUB_INITIAL_AGENT_TOKEN") (eq $key "INFRAHUB_SECURITY_SECRET_KEY") (eq $key "INFRAHUB_API_TOKEN"))) }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          {{- end }}
          {{- with .Values.infrahubServer.infrahubServer.envFromExistingSecret }}
          envFrom:
            - secretRef:
                name: {{ . }}
          {{- end }}
          image: {{ default .Values.global.imageRegistry .Values.infrahubDemoData.imageRegistry }}/{{ .Values.global.infrahubRepository }}:{{ .Values.global.infrahubTag | default .Chart.AppVersion }}
          imagePullPolicy: {{ default .Values.global.imagePullPolicy .Values.infrahubDemoData.imagePullPolicy }}
          name: infrahub-demo-data-job
          {{- with .Values.infrahubDemoData.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.infrahubDemoData.securityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
      restartPolicy: Never
{{- end }}
