---
# yamllint disable rule:truthy
name: Publish Helm Chart

on:
  workflow_dispatch:
    inputs:
      chart:
        type: string
        description: Which chart to publish
        required: true
      publish:
        type: boolean
        description: Wether to publish the Chart to Infrahub Private Registry
        required: false
        default: false
  workflow_call:
    inputs:
      chart:
        type: string
        description: Which chart to publish
        required: true
      publish:
        type: boolean
        description: Wether to publish the Chart to Infrahub Private Registry
        required: false
        default: false

jobs:
  publish-helm-chart:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Helm
        uses: azure/setup-helm@v4.3.0

      - name: Login to Helm Registry
        run: >
          helm registry login ${{ vars.HARBOR_HOST }}
          --username '${{ secrets.HARBOR_USERNAME }}'
          --password '${{ secrets.HARBOR_PASSWORD }}'

      - name: Package Helm Chart
        run: |
          helm package --dependency-update ./charts/${{ inputs.chart }}

      - name: Push Helm Chart to OCI Registry
        if: ${{ inputs.publish }}
        run: |
          helm push ${{ inputs.chart }}*.tgz oci://${{ vars.HARBOR_HOST }}/opsmill/chart

